@baseUrl = http://localhost:6688/api

### signup
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "fullname": "Alice Chen",
  "workspace": "acme",
  "email": "alice@acme.org",
  "password": "123456"
}

### signin
# @name signin
POST {{baseUrl}}/signin
Content-Type: application/json

{
  "email": "alice@acme.org",
  "password": "123456"
}

@auth_token = {{signin.response.body.token}}

### create chat
POST {{baseUrl}}/chat
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "acme",
  "members": [1, 2],
  "public": false
}

### get chat list
GET {{baseUrl}}/chat
Authorization: Bearer {{auth_token}}

### get user list
GET {{baseUrl}}/users
Authorization: Bearer {{auth_token}}

### upload files
POST {{baseUrl}}/upload
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=DummyBoundary

--DummyBoundary
Content-Disposition: form-data; filename="dummy.png"
Content-Type: application/octet-stream

< /Users/ohmycloud/dummy.png
--DummyBoundary
Content-Disposition: form-data; filename="hello.txt"

Hello, Raku!
--DummyBoundary--

### download file handler
GET {{baseUrl}}/files/1/8b7/230/ae7b0acf015add5234485a45efaf516413.png
Authorization: Bearer {{auth_token}}