### GET top stories

GET https://hacker-news.firebaseio.com/v0/topstories.json

### GET item

@id = 41742210

GET https://hacker-news.firebaseio.com/v0/item/{{id}}.json

### GET comments

@command_id = 41742648

GET https://hacker-news.firebaseio.com/v0/item/{{command_id}}.json

### GET user

@user_id = CaptainOfCoit

GET https://hacker-news.firebaseio.com/v0/user/{{user_id}}.json