server:
  port: 6688
  db_url: postgres://postgres:password@127.0.0.1:5432/chat
auth:
  sk: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEINzgOtY3KBQGJkMoTubmxOb6T5crJyijtcCNpY//8f3T
    -----END PRIVATE KEY-----
  pk: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAPA2yi7McLfXH5SZJI+S7XPtJVz3xvFtp1r+TwDFWmh4=
    -----END PUBLIC KEY-----
